services:
    rate-nodejs-test:
        container_name: rate-nodejs-test
        build: docker/nodejs
        command: node -e 'setInterval(() => {}, 1000)'
        env_file:
            - .env.test
        volumes:
            - ./src:/app
        working_dir: /app
        depends_on:
            - rate-postgres-test
            - rate-redis-test

    rate-postgres-test:
        container_name: rate-postgres-test
        image: postgres:15.6
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        command: "postgres -c 'client_min_messages=error'"

    rate-redis-test:
        container_name: rate-redis-test
        image: redis:alpine
